version: '3'

services:
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./resources/public:/usr/share/nginx/html
    depends_on:
      - api

  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - ENV=prod
      - REDIS_URI=redis://db:6379
    depends_on:
      - db

  db:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - data:/data

volumes:
  data:
